# Generated by Django 5.0.7 on 2024-08-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loops', '0002_loop_bpm_loop_categoria_loop_escala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='loop',
            name='categoria',
            field=models.CharField(default='Trap', max_length=50),
        ),
        migrations.AlterField(
            model_name='loop',
            name='escala',
            field=models.CharField(default='Fm', max_length=50),
        ),
    ]
